// POST /api/nova/zip — export project as ZIP (pure JS, no binary dependency)
// Optional body.provenance: { missionId, mission, qualityScore, healthScore, engineConfig, events }
//   — when provided, adds NOVA_PROVENANCE.md + build-events.json + engine-config.json
//   to the ZIP for reproducibility (CC: Build provenance export).
import type { NextRequest } from 'next/server';
import archiver from 'archiver';
import { Writable } from 'node:stream';
import { db } from '@/lib/db';
import { getAllMissionEvents } from '@/lib/mission-stream';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
export const maxDuration = 30;

export async function POST(request: NextRequest): Promise<Response> {
  let body: any;
  try { body = await request.json(); } catch {
    return Response.json({ ok: false, error: 'Invalid JSON' }, { status: 400 });
  }

  const files = body?.files;
  if (!files || !Array.isArray(files) || files.length === 0) {
    return Response.json({ ok: false, error: 'No files provided' }, { status: 400 });
  }

  const provenance = body?.provenance; // optional
  const includeProvenance = !!provenance?.missionId;

  try {
    // If provenance requested and not pre-supplied, fetch from DB
    let events: any[] = provenance?.events || [];
    let checkpoint: any = null;
    if (includeProvenance && events.length === 0) {
      try { events = await getAllMissionEvents(provenance.missionId); } catch {}
    }
    if (includeProvenance && !provenance?.engineConfig) {
      try {
        checkpoint = await db.buildCheckpoint.findUnique({ where: { missionId: provenance.missionId } });
        if (checkpoint) {
          provenance.engineConfig = checkpoint.engineConfig;
          provenance.healthScore = checkpoint.healthScore;
          provenance.qualityScore = provenance.qualityScore ?? checkpoint.qualityScore;
        }
      } catch {}
    }

    const chunks: Buffer[] = [];
    const archive = archiver('zip', { zlib: { level: 9 } });
    const writable = new Writable({
      write(chunk: Buffer, _encoding: string, callback: () => void) {
        chunks.push(chunk);
        callback();
      },
    });
    archive.pipe(writable);

    // Add all project files
    for (const f of files) {
      archive.append(f.content, { name: f.path });
    }

    // Add .gitignore if not present
    if (!files.some((f: any) => f.path === '.gitignore')) {
      archive.append('node_modules/\n.env\ndist/\nbuild/\n*.log\nNOVA_PROVENANCE.md\nbuild-events.json\nengine-config.json\n', { name: '.gitignore' });
    }
    // Add LICENSE if not present
    if (!files.some((f: any) => f.path === 'LICENSE')) {
      archive.append(`MIT License\n\nCopyright (c) ${new Date().getFullYear()}\n`, { name: 'LICENSE' });
    }

    // ── Provenance files (CC) ──
    if (includeProvenance) {
      // 1. NOVA_PROVENANCE.md — human-readable summary
      const md = `# NOVA Build Provenance

This file documents how the project was built by NOVA, for full reproducibility.

## Build Metadata
- **Mission**: ${provenance.mission || '(unknown)'}
- **Mission ID**: ${provenance.missionId}
- **Quality Score**: ${provenance.qualityScore ?? '—'}/10
- **Health Score**: ${provenance.healthScore ?? '—'}/100
- **Build Date**: ${new Date().toISOString()}

## Engine Configuration
\`\`\`json
${provenance.engineConfig || '{}'}
\`\`\`

## Build Events
${events.length} events recorded. See \`build-events.json\` for the full event stream.

## Files
${files.map((f: any) => `- \`${f.path}\` (${(f.content || '').split('\\n').length} lines)`).join('\\n')}

---
_Generated by NOVA — reproducibility-first._
`;
      archive.append(md, { name: 'NOVA_PROVENANCE.md' });
      // 2. build-events.json — full event stream
      archive.append(JSON.stringify(events, null, 2), { name: 'build-events.json' });
      // 3. engine-config.json — engine config snapshot
      archive.append(provenance.engineConfig || '{}', { name: 'engine-config.json' });
    }

    await archive.finalize();

    const zipBuffer = Buffer.concat(chunks);
    const base64 = zipBuffer.toString('base64');

    return Response.json({
      ok: true,
      zip: base64,
      filename: (body.name || 'project').replace(/[^a-zA-Z0-9]/g, '_') + '.zip',
      size: zipBuffer.length,
      provenanceIncluded: includeProvenance,
    });
  } catch (err) {
    return Response.json({
      ok: false,
      error: err instanceof Error ? err.message : String(err),
    }, { status: 500 });
  }
}

