// Additional tests for cycle 7 fixes
import { describe, it, expect } from 'bun:test'
import { stripCodeFences, looksLikeHtml, injectCsp } from '../src/lib/html-utils'

describe('looksLikeHtml — comment edge cases', () => {
  it('accepts HTML starting with comment then doctype', () => {
    // LLM might add an HTML comment before the doctype
    const html = '<!-- generated by NOVA -->\n<!DOCTYPE html>'
    // trimStart removes leading whitespace but not comments
    // So this should FAIL (comment isn't whitespace)
    expect(looksLikeHtml(html)).toBe(false)
  })

  it('accepts HTML with leading newlines and tabs', () => {
    expect(looksLikeHtml('\n\t\n  <!DOCTYPE html>')).toBe(true)
  })

  it('rejects empty string', () => {
    expect(looksLikeHtml('')).toBe(false)
  })

  it('rejects only whitespace', () => {
    expect(looksLikeHtml('   \n\t  ')).toBe(false)
  })
})

describe('injectCsp — additional edge cases', () => {
  it('handles HTML with multiple heads (invalid but defensive)', () => {
    // Browsers parse this in weird ways; we should inject in the first <head>
    const html = '<!DOCTYPE html><html><head></head><head></head></html>'
    const result = injectCsp(html)
    expect(result).toContain('Content-Security-Policy')
    // Should only inject once
    const cspCount = (result.match(/Content-Security-Policy/gi) || []).length
    expect(cspCount).toBe(1)
  })

  it('handles self-closing head tag', () => {
    // Invalid HTML but defensive
    const html = '<!DOCTYPE html><html><head/></html>'
    const result = injectCsp(html)
    // Should still inject CSP somewhere
    expect(result).toContain('Content-Security-Policy')
  })

  it('preserves existing meta tags in head', () => {
    const html = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"></head></html>'
    const result = injectCsp(html)
    expect(result).toContain('charset="UTF-8"')
    expect(result).toContain('name="viewport"')
    expect(result).toContain('Content-Security-Policy')
  })
})

describe('stripCodeFences — additional edge cases', () => {
  it('handles fences with extra whitespace', () => {
    const input = '```  html  \n<!DOCTYPE html>\n```'
    const result = stripCodeFences(input)
    expect(result).toBe('<!DOCTYPE html>')
  })

  it('handles fences with Windows line endings', () => {
    const input = '```html\r\n<!DOCTYPE html>\r\n```'
    const result = stripCodeFences(input)
    // \r\n should be handled by the regex (\s matches \r)
    expect(result).toContain('<!DOCTYPE html>')
  })

  it('handles nested backticks in content', () => {
    // LLM might include backticks in the HTML (e.g., in a <code> block)
    const input = '```html\n<!DOCTYPE html><body>`code`</body>\n```'
    const result = stripCodeFences(input)
    expect(result).toContain('<!DOCTYPE html>')
    expect(result).toContain('`code`')
  })
})
