// Tests for roast cycle #4 fixes
import { describe, it, expect } from 'bun:test'
import { injectCsp, looksLikeHtml } from '../src/lib/html-utils'
import { extractBalancedJson } from '../src/lib/json-extract'

describe('injectCsp — always strips existing CSP (roast #4 security fix)', () => {
  it('strips permissive CSP and injects strict CSP', () => {
    const html = '<!DOCTYPE html><html><head><meta http-equiv="Content-Security-Policy" content="default-src *"></head></html>'
    const result = injectCsp(html)
    expect(result).not.toContain('default-src *')
    expect(result).toContain("connect-src 'none'")
  })

  it('strips multiple existing CSP metas and injects one strict CSP', () => {
    const html = '<!DOCTYPE html><html><head><meta http-equiv="Content-Security-Policy" content="default-src *"><meta http-equiv="Content-Security-Policy" content="script-src *"></head></html>'
    const result = injectCsp(html)
    const cspCount = (result.match(/Content-Security-Policy/gi) || []).length
    expect(cspCount).toBe(1) // Only NOVA's strict CSP
    expect(result).toContain("connect-src 'none'")
  })
})

describe('looksLikeHtml — strips leading comments (roast #4 fix)', () => {
  it('accepts HTML with leading comment before doctype', () => {
    expect(looksLikeHtml('<!-- generated by NOVA -->\n<!DOCTYPE html>')).toBe(true)
  })

  it('accepts HTML with leading comment before <html>', () => {
    expect(looksLikeHtml('<!-- comment --><html></html>')).toBe(true)
  })

  it('still rejects plain text', () => {
    expect(looksLikeHtml('just text')).toBe(false)
  })
})

describe('extractBalancedJson — robust JSON extraction (roast #4 fix)', () => {
  it('extracts JSON from prose', () => {
    const text = 'Here is the plan:\n{"type":"game","title":"Snake"}\nHope this helps!'
    expect(extractBalancedJson(text)).toEqual({ type: 'game', title: 'Snake' })
  })

  it('extracts JSON from code fences', () => {
    const text = '```json\n{"type":"app","features":["a","b"]}\n```'
    expect(extractBalancedJson(text)).toEqual({ type: 'app', features: ['a', 'b'] })
  })

  it('handles nested braces in strings', () => {
    const text = '{"a": "this has a } in it", "b": 2}'
    expect(extractBalancedJson(text)).toEqual({ a: 'this has a } in it', b: 2 })
  })

  it('handles nested objects', () => {
    const text = '{"outer": {"inner": {"deep": true}}}'
    expect(extractBalancedJson(text)).toEqual({ outer: { inner: { deep: true } } })
  })

  it('handles escaped quotes in strings', () => {
    const text = '{"a": "he said \\"hello\\""}'
    expect(extractBalancedJson(text)).toEqual({ a: 'he said "hello"' })
  })

  it('returns null when no JSON found (v29.38: changed from throw to null)', () => {
    expect(extractBalancedJson('no json here')).toBeNull()
  })

  it('does not grab trailing prose with a }', () => {
    const text = '{"a":1}\n\nHope this helps!}'
    expect(extractBalancedJson(text)).toEqual({ a: 1 })
  })

  it('handles multiple JSON objects (takes first balanced)', () => {
    const text = '{"a":1} {"b":2}'
    expect(extractBalancedJson(text)).toEqual({ a: 1 })
  })
})
